---
- name: Installing Required Packages in Jenkins Worker Machine
  host: jenkins-slave
  become: true
  tasks:
  - name: update repository
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600
  - name: install java-11
    ansible.builtin.apt:
      name: openjdk-11-jre
      state: present
  - name: create directory jenkins
    ansible.builtin.file:
      path: /home/padmajaganji111/jenkins
      state: directory
      mode: '0755'
      owner: padmajaganji111
      group: padmajaganji111
  - name: Download Jdk-17.0.2
    ansible.builtin.get_url:
      url: https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
      dest: /opt/
  - name: unzip the jdk-17
    ansible.builtin.unarchive:
      src: /opt/openjdk-17.0.2_linux-x64_bin.tar.gz
      dest: /opt/
      remote_src: yes
  - name: Download maven-3.8.8
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz
      dest: /opt/
  - name: Unzip maven-3.8.8
    ansible.builtin.unarchive:
      src: /opt/apache-maven-3.8.8-bin.tar.gz
      dest: /opt/
      remote_src: yes